//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ripple.Signing.Tests.Properties
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ripple.Signing.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to rDS9jdPZqqoViLhqcHUiAf9pUBoGPo3g2k sseSp5dQDwgNu8dp5pSpBediiPCdt
        ///rJL9RSA3xYVAhje4s3ogMJoWYa7T7Fte8w shv2FGMxxTTcyfhpb7ckQAZVJ2YuW
        ///rw14hrs6a4xsD3ciFQWyVrZu4EXDzwCSGD ssHPUmtgfhECFd6UfKHDtTCc5BkjM
        ///rGtFyi87gRWaThUoMjLvonBC87qUQLKEG1 ssN8pUPYUaHobNRyrD3iajnvXqSck
        ///rJRtd68JTHL7oi1d3G5XvGui3TF8LLj6qn sa9scPofk2egkwb93s7r5W9EEm2wz
        ///rL1PTFrnsAYrvi9DEyddLoqxwb3v8kDanC shcFiVNieAK56L3sJR2o6qwYTi8Bh
        ///rJAYthx1XJZrWzFFmMPkragusP56YpXRsp ssHj1pcKZQ1anetLwBnmZxk8C6UWb
        ///rLo64g8yTrQ3ETsQ1pybfp1rSwjdDoLg1m shgMbKMZtL7dBgu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ecdsa_100
        {
            get
            {
                return ResourceManager.GetString("ecdsa_100", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to r4XaX1cb4M1F8HY5Q9LMv3HtMiZcDXp2RK shscYAchQerotzLVJ9nF1K15vFrY5
        ///rNeYeDCNQ5Futmmb2mGfMLvz3rpjbvzNgR sahFrTw9wPSYWW4BduMHWwJq9L5Jo
        ///rMrSqqHQuvz1UdUsdNoU5PBvmUbYTrgxPj saNSVgwL4p47jYnRFefeLiFT7pxTY
        ///r9ZxywsFqJuCKfDT7gV39cHqfBaJJhKCMu saraqZLRU132zcWDUkAA2w2eaExKX
        ///rEaS7fFzmz2NvMFEZgXjSnoLWjJk9khkqk shxgEcgL7CaZsUfqCB7UDCLqQsjRA
        ///rD6Hikcsc2P5PtZVX1AKFYUQaNb5Ri72up spqRv3nTPjDUJhDBo4vR56sVkg58k
        ///rN9h1MSRBCXVUmJW5DNG9T5UZKNQQREXxx snfnjGJd3sWLE3jU4RvkRTsMZXW2p
        ///rBPmGABtzZzt7PRvBYTgfowKfbdhw7adpJ sanExo2CHmaNGxu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ecdsa_1000000
        {
            get
            {
                return ResourceManager.GetString("ecdsa_1000000", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to rsGDFUSWYEnsYoUvPXLsrc4rP7DhY6N5GA sEdTPrYdDrQZLVrZrfprnYKZN9p1Hpx
        ///rPrYhLL3K6iYJ247VW3BpzDb4fs54xhWhH sEdTazhUgnGYYe24maoBZCLF2CCKTjg
        ///rsVcpSn4i8LF2rDPZ6TuyW17opvBGXFRTm sEd7sGMzBUp4ACwe99SUs1zpUuZzjDG
        ///rnCDThdfoJwXd4mDoTwoy2upivd1BPYB36 sEdTqmghvXszUatn9FnsCmfE9s2t5gL
        ///rPiUDFjrXvJKVGegW3KPnJbztXzKwwKaCZ sEd7DVHfPeSex4n9Y15Bt7pKYWkY6Pg
        ///rht7jgTRoaWqP7KRevb87ZRQMn3SpbeCty sEdTWkUYfAA3otMWXkY6E2aURr7AFZ2
        ///rUrrGYqpy88aTvNywrhfwj9kH3JEepMHxu sEd7BC8ZBLtzMJRzg1hdRzCDZ1mPG29
        ///r3gpMCqZKf2kC9v2XZwYudJhQTkGo9ofjZ s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ed25519_1000000
        {
            get
            {
                return ResourceManager.GetString("ed25519_1000000", resourceCulture);
            }
        }
    }
}
