//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ripple.Binary.Codec.Tests.Properties {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("xrpl_c_tests.Ripple.Binary.Codec.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static byte[] DataDrivenTests {
            get {
                object obj = ResourceManager.GetObject("DataDrivenTests", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] LedgerFull38129 {
            get {
                object obj = ResourceManager.GetObject("LedgerFull38129", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] LedgerFull40000 {
            get {
                object obj = ResourceManager.GetObject("LedgerFull40000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static string TestResource {
            get {
                return ResourceManager.GetString("TestResource", resourceCulture);
            }
        }
        
        public static byte[] TransactionsWithMeta {
            get {
                object obj = ResourceManager.GetObject("TransactionsWithMeta", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
